package uz.prod.backcrm.utills.constants;

public interface Message {

    String DELETED_SUCCESSFULLY = "DELETED_SUCCESSFULLY";
    String DELETE_FAILED= "DELETE_FAILED";
    String EDIT = "_EDIT";
    String CREATE = "_CREATE";

    String SUCCESSFULLY = "SUCCESSFULLY";

    String USERNAME_NOT_FOUND = "USERNAME_NOT_FOUND";

    String USER_ALREADY_REGISTERED = "USER_ALREADY_REGISTERED";
    String USER_NOT_FOUND_OR_DISABLED = "USER_NOT_FOUND_OR_DISABLED";
    String LOGIN_OR_PASSWORD_ERROR = "LOGIN_OR_PASSWORD_ERROR";

    String PASSWORD_SHOULD_NOT_BE_EMPTY = "PASSWORD_SHOULD_NOT_BE_EMPTY";

    String PRE_PASSWORD_SHOULD_NOT_BE_EMPTY = "PRE_PASSWORD_SHOULD_NOT_BE_EMPTY";

    String SHOULD_NOT_BE_EMPTY = "SHOULD_NOT_BE_EMPTY";
    String SMS_CODE_MUST_BE_BETWEEN = "SMS_CODE_MUST_BE_BETWEEN";
    String SMS_CODE_SUCCESSFULLY_SEND = "SMS_CODE_SUCCESSFULLY_SEND";

    String NOT_FOUND_ROLE = "NOT_FOUND_ROLE";
    String PASSWORDS_AND_PRE_PASSWORD_NOT_EQUAL = "PASSWORDS_AND_PRE_PASSWORD_NOT_EQUAL";

    String CONFIRMATION_CODE_INCORRECT = "CONFIRMATION_CODE_INCORRECT";

    String NOT_VERIFIED = "NOT_VERIFIED";
    String ONLINE_FORM_ADDED_SUCCESSFULLY = "ONLINE_FORM_ADDED_SUCCESSFULLY";
    String SOMETHING_WENT_EMPTY = "SOMETHING_WENT_EMPTY";
    String SCHOOL_NAME_OR_PHONE_NUMBER_OR_EMAIL_ALREADY_EXISTED = "SCHOOL_NAME_OR_PHONE_NUMBER_OR_EMAIL_ALREADY_EXISTED";
    String ID_NOT_FOUND = "ID_NOT_FOUND";
    String THIS_EMAIL_ALREADY_EXISTED = "THIS_EMAIL_ALREADY_EXISTED";
    String YOU_SUBSCRIBED_TO_OUR_NEWSLETTER = "YOU_SUBSCRIBED_TO_OUR_NEWSLETTER";
    String SCHOOL_APPROVED = "SCHOOL_APPROVED";
    String SCHOOL_REJECTED = "SCHOOL_REJECTED";
    String WRONG_PHONE_NUMBER_FORMAT = "WRONG_PHONE_NUMBER_FORMAT";
    String WRONG_EMAIL_FORMAT = "WRONG_EMAIL_FORMAT";

    String NOT_FOUND_EMAIL = "NOT_FOUND_EMAIL";
    String FILE_IS_FORBIDDEN = "FILE_IS_FORBIDDEN";
    String SAVED_SUCCESSFULLY = "SAVED_SUCCESSFULLY";
    String SEND_SUCCESSFULLY = "SEND_SUCCESSFULLY";
    String UPDATED_SUCCESSFULLY = "UPDATED_SUCCESSFULLY";

    String SHOULD_NOT_BE_NULL = "SHOULD_NOT_BE_NULL";

    String ID_SHOULD_BE_LONG = "ID_SHOULD_BE_LONG";
    String ID_SHOULD_BE_UUID = "ID_SHOULD_BE_UUID";

    String EMPTY_COOKIE = "EMPTY_COOKIE";

    String NOT_STANDARD = "NOT_STANDARD";
    String NOT_FOUND_USER = "NOT_FOUND_USER";
}


