server:
  port: 8090
spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  main:
    allow-circular-references: false
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/back_crm
    username: postgres
    password: root123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        jdbc:
          lob:
            non_contextual_creation: true
  sql:
    init:
      mode: never


app:
  jwt:
    access:
      token:
        key: "--9w5e-2fe-f2-wf4-f.f5-wef.s.65fwaa.5f%^&@#$2"
        expiration-in-ms: 43200000